[package]
name = "svg_metadata"
version = "0.2.1"
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
edition = "2018"
description = "Extracts metadata like the viewBox from SVG graphics"
license = "Apache-2.0/MIT"
keywords = ["svg", "graphics", "image", "metadata" ]
homepage = "https://github.com/mre/svg-metadata"
categories = [
    "graphics", 
    "multimedia", 
    "parsing"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.7.0"
regex = "1.2.1"
lazy_static = "1.3.0"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"
